// Generated by Wrangler on Fri Sep 20 2024 22:18:18 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
