// Generated by Wrangler on Sun Sep 22 2024 16:07:42 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	NEXTAUTH_SECRET: string;
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	GITHUB_ID: string;
	GITHUB_SECRET: string;
	DB: D1Database;
}
